import { initializeTestEnvironment, assertSucceeds, assertFails } from "@firebase/rules-unit-testing";
import { readFileSync } from "fs";
import { doc, setDoc, getDoc, updateDoc, deleteDoc, getDocs, collection } from "firebase/firestore";
const env = await initializeTestEnvironment({ projectId: "demo-test", firestore: { rules: readFileSync("../../firestore.rules", "utf8"), host: "127.0.0.1", port: 8081 } });
await env.clearFirestore();
let pass = 0, fail = 0;
const t = async (name, fn) => { try { await fn(); pass++; console.log("  ok  ", name); } catch (e) { fail++; console.log("  FAIL", name, "-", String(e.message).slice(0, 120)); } };
const R = "rooms/r00m-Abc123xy", now = () => Date.now();
await env.withSecurityRulesDisabled(async (c) => {
  const db = c.firestore();
  await setDoc(doc(db, "admins/boss"), { note: "owner" });
  await setDoc(doc(db, R + "/doubts/d1"), { title: "Hello there", body: "x", subject: "DSP", authorId: "stud-device-1", ownerUid: "someone", authorName: "S", createdAt: now(), reports: ["a|o", "b|a"] });
  await setDoc(doc(db, R + "/replies/r1"), { parentId: "d1", parentColl: "doubts", body: "hi hi", authorId: "stud-device-1", ownerUid: "someone", authorName: "S", createdAt: now() });
  await setDoc(doc(db, "collegeRequests/q1"), { name: "My College", city: "X", role: "Student", contact: "", consent: true, createdAt: now() });
  await setDoc(doc(db, "plusInterest/p1"), { email: "", college: "RGUKT", features: [], price: "x", createdAt: now() });
});
const admin = env.authenticatedContext("boss", { email: "me@x.com", email_verified: true }).firestore();
const adminNoVerify = env.authenticatedContext("boss", { email: "me@x.com", email_verified: false }).firestore();
const student = env.authenticatedContext("stud", { email: "s@x.com", email_verified: true }).firestore();
const anon = env.authenticatedContext("anon1").firestore();
console.log("who is an admin");
await t("admin can read own admins doc", () => assertSucceeds(getDoc(doc(admin, "admins/boss"))));
await t("nobody can create an admins doc from the app", () => assertFails(setDoc(doc(admin, "admins/me2"), { x: 1 })));
await t("a student cannot read someone else's admins doc", () => assertFails(getDoc(doc(student, "admins/boss"))));
console.log("moderation");
await t("admin hides someone else's post", () => assertSucceeds(updateDoc(doc(admin, R + "/doubts/d1"), { deleted: true })));
await t("admin restores it and clears reports", () => assertSucceeds(updateDoc(doc(admin, R + "/doubts/d1"), { deleted: false, reports: [] })));
await t("admin hides a reply", () => assertSucceeds(updateDoc(doc(admin, R + "/replies/r1"), { deleted: true })));
await t("admin cannot edit the text of a post", () => assertFails(updateDoc(doc(admin, R + "/doubts/d1"), { title: "Changed by admin" })));
await t("admin with an unverified email is not an admin", () => assertFails(updateDoc(doc(adminNoVerify, R + "/doubts/d1"), { deleted: true })));
await t("a student cannot hide someone else's post", () => assertFails(updateDoc(doc(student, R + "/doubts/d1"), { deleted: true })));
await t("admin cannot hard-delete", () => assertFails(deleteDoc(doc(admin, R + "/doubts/d1"))));
console.log("blocking devices");
await t("admin blocks a device", () => assertSucceeds(setDoc(doc(admin, R + "/blocked/stud-device-1"), { reason: "abuse", by: "boss", at: now() })));
await t("student cannot block", () => assertFails(setDoc(doc(student, R + "/blocked/other-device-1"), { reason: "x", by: "stud", at: now() })));
await t("blocked device can no longer post", () => assertFails(setDoc(doc(anon, R + "/doubts/dz"), { title: "Hello there", body: "x", subject: "DSP", authorId: "stud-device-1", authorName: "S", createdAt: now() })));
await t("admin unblocks", () => assertSucceeds(deleteDoc(doc(admin, R + "/blocked/stud-device-1"))));
await t("...and the student can post again", () => assertSucceeds(setDoc(doc(anon, R + "/doubts/dy"), { title: "Hello there", body: "x", subject: "DSP", authorId: "stud-device-1", authorName: "S", createdAt: now() })));
console.log("colleges, requests, survey, log");
const college = (extra = {}) => ({ name: "New University", room: "k7Qm2xPa9Rtz", state: "Kerala", campuses: ["MAIN"], subjects: ["Maths"], features: { bot: false }, domains: ["new.edu.in"], requireVerified: false, listed: true, enabled: true, updatedAt: now(), ...extra });
await t("admin creates a college", () => assertSucceeds(setDoc(doc(admin, "colleges/new-university"), college())));
await t("admin edits a college", () => assertSucceeds(setDoc(doc(admin, "colleges/new-university"), college({ tagline: "Learn together" }))));
await t("student cannot write a college", () => assertFails(setDoc(doc(student, "colleges/sneaky"), college())));
await t("college with a bad room id is refused", () => assertFails(setDoc(doc(admin, "colleges/bad-room"), college({ room: "a/b" }))));
await t("college with an unknown field is refused", () => assertFails(setDoc(doc(admin, "colleges/bad-field"), college({ hack: 1 }))));
await t("college with a bad link name is refused", () => assertFails(setDoc(doc(admin, "colleges/Bad_Name"), college())));
await t("admin reads college requests and survey answers", async () => { await assertSucceeds(getDocs(collection(admin, "collegeRequests"))); await assertSucceeds(getDocs(collection(admin, "plusInterest"))); });
await t("students still cannot read requests or survey answers", async () => { await assertFails(getDocs(collection(student, "collegeRequests"))); await assertFails(getDocs(collection(student, "plusInterest"))); });
await t("admin deletes a handled college request", () => assertSucceeds(deleteDoc(doc(admin, "collegeRequests/q1"))));
await t("admin writes an audit entry", () => assertSucceeds(setDoc(doc(admin, "adminLog/l1"), { by: "boss", action: "hide", target: "doubts/d1", room: "rgukt", note: "spam", at: now() })));
await t("audit entries cannot be edited or removed", async () => { await assertFails(updateDoc(doc(admin, "adminLog/l1"), { note: "x" })); await assertFails(deleteDoc(doc(admin, "adminLog/l1"))); });
await t("students cannot read or write the audit log", async () => { await assertFails(getDoc(doc(student, "adminLog/l1"))); await assertFails(setDoc(doc(student, "adminLog/l2"), { by: "s", action: "x", at: now() })); });
await t("admin sets config/plus.required", () => assertSucceeds(setDoc(doc(admin, "config/plus"), { required: true })));
await t("student cannot read config", () => assertFails(getDoc(doc(student, "config/plus"))));
console.log("paper vault");
const paper = (extra = {}) => ({ title: "Data Structures End 2023", subject: "DSA", year: 2023, exam: "End", link: "https://drive.google.com/file/d/abc/view", solution: "", note: "", createdAt: now(), ...extra });
await t("admin adds a paper", () => assertSucceeds(setDoc(doc(admin, R + "/papers/p1"), paper())));
await t("student can read papers", () => assertSucceeds(getDocs(collection(student, R + "/papers"))));
await t("student cannot add a paper", () => assertFails(setDoc(doc(student, R + "/papers/p2"), paper())));
await t("student cannot delete a paper", () => assertFails(deleteDoc(doc(student, R + "/papers/p1"))));
await t("paper with a non-https link is refused", () => assertFails(setDoc(doc(admin, R + "/papers/p3"), paper({ link: "http://x.com/a.pdf" }))));
await t("paper with a javascript link is refused", () => assertFails(setDoc(doc(admin, R + "/papers/p4"), paper({ link: "javascript:alert(1)" }))));
await t("paper with a bad year is refused", () => assertFails(setDoc(doc(admin, R + "/papers/p5"), paper({ year: 1800 }))));
await t("paper with an unknown field is refused", () => assertFails(setDoc(doc(admin, R + "/papers/p6"), paper({ hack: 1 }))));
await t("paper with a solution link is accepted", () => assertSucceeds(setDoc(doc(admin, R + "/papers/p7"), paper({ solution: "https://example.com/sol.pdf" }))));
await t("admin removes a paper", () => assertSucceeds(deleteDoc(doc(admin, R + "/papers/p7"))));
console.log("official notices");
const notice = (extra = {}) => ({ title: "Exam timetable out", body: "Check the portal.", pinned: true, createdAt: now(), ...extra });
await t("admin posts a notice", () => assertSucceeds(setDoc(doc(admin, R + "/notices/n1"), notice())));
await t("student reads notices", () => assertSucceeds(getDocs(collection(student, R + "/notices"))));
await t("student cannot post a notice", () => assertFails(setDoc(doc(student, R + "/notices/n2"), notice())));
await t("notice with a non-https link is refused", () => assertFails(setDoc(doc(admin, R + "/notices/n3"), notice({ link: "javascript:alert(1)" }))));
await t("notice with an unknown field is refused", () => assertFails(setDoc(doc(admin, R + "/notices/n4"), notice({ hack: 1 }))));
await t("admin archives a notice", () => assertSucceeds(setDoc(doc(admin, R + "/notices/n1"), notice({ deleted: true }))));
console.log("referral codes");
const longUid = "abcdefghijklmnopqrstuvwxyz12", rc = env.authenticatedContext(longUid).firestore();
await t("student registers own referral code", () => assertSucceeds(setDoc(doc(rc, "refCodes/abcdefghij"), { uid: longUid, createdAt: now() })));
await t("student cannot register someone else's code", () => assertFails(setDoc(doc(rc, "refCodes/zzzzzzzzzz"), { uid: longUid, createdAt: now() })));
await t("student cannot claim a code for another uid", () => assertFails(setDoc(doc(rc, "refCodes/abcdefghij2"), { uid: "other", createdAt: now() })));
await t("nobody can read or change codes from the app", async () => { await assertFails(getDoc(doc(rc, "refCodes/abcdefghij"))); await assertFails(updateDoc(doc(rc, "refCodes/abcdefghij"), { uid: "x" })); await assertFails(deleteDoc(doc(rc, "refCodes/abcdefghij"))); });
console.log("promo codes");
const promo = (extra = {}) => ({ percent: 30, plan: "any", until: now() + 864e5 * 30, maxUses: 100, used: 0, active: true, note: "Exam season", createdAt: now(), ...extra });
await t("admin creates a promo code", () => assertSucceeds(setDoc(doc(admin, "promoCodes/EXAM30"), promo())));
await t("student cannot read or create promo codes", async () => { await assertFails(getDoc(doc(student, "promoCodes/EXAM30"))); await assertFails(setDoc(doc(student, "promoCodes/FREE90"), promo({ percent: 90 }))); });
await t("promo with 100% off is refused", () => assertFails(setDoc(doc(admin, "promoCodes/FREE100"), promo({ percent: 100 }))));
await t("promo starting with used > 0 is refused", () => assertFails(setDoc(doc(admin, "promoCodes/USED1"), promo({ used: 5 }))));
await t("promo with a lowercase or short code is refused", async () => { await assertFails(setDoc(doc(admin, "promoCodes/exam30x"), promo())); await assertFails(setDoc(doc(admin, "promoCodes/AB"), promo())); });
await t("admin can switch a code off but not change the discount or usage", async () => { await assertSucceeds(updateDoc(doc(admin, "promoCodes/EXAM30"), { active: false })); await assertFails(updateDoc(doc(admin, "promoCodes/EXAM30"), { percent: 90 })); await assertFails(updateDoc(doc(admin, "promoCodes/EXAM30"), { used: 5 })); });
console.log("flash sale");
const sale = (extra = {}) => ({ title: "Flash sale: 30% off", text: "Today only", code: "EXAM30", until: now() + 864e5, active: true, updatedAt: now(), ...extra });
await t("admin sets the flash sale", () => assertSucceeds(setDoc(doc(admin, "sales/current"), sale())));
await t("student reads the flash sale", () => assertSucceeds(getDoc(doc(student, "sales/current"))));
await t("student cannot change the flash sale", () => assertFails(setDoc(doc(student, "sales/current"), sale({ title: "Hacked sale" }))));
await t("only the document 'current' is allowed", () => assertFails(setDoc(doc(admin, "sales/other"), sale())));
await t("a bad code or extra field is refused", async () => { await assertFails(setDoc(doc(admin, "sales/current"), sale({ code: "bad code!" }))); await assertFails(setDoc(doc(admin, "sales/current"), sale({ hack: 1 }))); });
await t("admin switches the sale off", () => assertSucceeds(setDoc(doc(admin, "sales/current"), sale({ active: false }))));
console.log(`\n${pass} passed, ${fail} failed`);
await env.cleanup(); process.exit(fail ? 1 : 0);
