import { initializeTestEnvironment, assertSucceeds, assertFails } from "@firebase/rules-unit-testing";
import { readFileSync } from "fs";
import { doc, setDoc, getDoc, updateDoc, deleteDoc, getDocs, collection } from "firebase/firestore";
const env = await initializeTestEnvironment({ projectId: "demo-test", firestore: { rules: readFileSync("../../firestore.rules", "utf8"), host: "127.0.0.1", port: 8081 } });
await env.clearFirestore();
let pass = 0, fail = 0;
const t = async (name, fn) => { try { await fn(); pass++; console.log("  ok  ", name); } catch (e) { fail++; console.log("  FAIL", name, "-", String(e.message).slice(0, 120)); } };
const R = "rooms/r00m-Abc123xy", now = () => Date.now();
await env.withSecurityRulesDisabled(async (c) => {
  const db = c.firestore();
  await setDoc(doc(db, "admins/boss"), { note: "owner" });
  await setDoc(doc(db, R + "/doubts/d1"), { title: "Hello there", body: "x", subject: "DSP", authorId: "stud-device-1", ownerUid: "someone", authorName: "S", createdAt: now(), reports: ["a|o", "b|a"] });
  await setDoc(doc(db, R + "/replies/r1"), { parentId: "d1", parentColl: "doubts", body: "hi hi", authorId: "stud-device-1", ownerUid: "someone", authorName: "S", createdAt: now() });
  await setDoc(doc(db, "collegeRequests/q1"), { name: "My College", city: "X", role: "Student", contact: "", consent: true, createdAt: now() });
  await setDoc(doc(db, "plusInterest/p1"), { email: "", college: "RGUKT", features: [], price: "x", createdAt: now() });
});
const admin = env.authenticatedContext("boss", { email: "me@x.com", email_verified: true }).firestore();
const adminNoVerify = env.authenticatedContext("boss", { email: "me@x.com", email_verified: false }).firestore();
const student = env.authenticatedContext("stud", { email: "s@x.com", email_verified: true }).firestore();
const anon = env.authenticatedContext("anon1").firestore();
console.log("who is an admin");
await t("admin can read own admins doc", () => assertSucceeds(getDoc(doc(admin, "admins/boss"))));
await t("nobody can create an admins doc from the app", () => assertFails(setDoc(doc(admin, "admins/me2"), { x: 1 })));
await t("a student cannot read someone else's admins doc", () => assertFails(getDoc(doc(student, "admins/boss"))));
console.log("moderation");
await t("admin hides someone else's post", () => assertSucceeds(updateDoc(doc(admin, R + "/doubts/d1"), { deleted: true })));
await t("admin restores it and clears reports", () => assertSucceeds(updateDoc(doc(admin, R + "/doubts/d1"), { deleted: false, reports: [] })));
await t("admin hides a reply", () => assertSucceeds(updateDoc(doc(admin, R + "/replies/r1"), { deleted: true })));
await t("admin cannot edit the text of a post", () => assertFails(updateDoc(doc(admin, R + "/doubts/d1"), { title: "Changed by admin" })));
await t("admin with an unverified email is not an admin", () => assertFails(updateDoc(doc(adminNoVerify, R + "/doubts/d1"), { deleted: true })));
await t("a student cannot hide someone else's post", () => assertFails(updateDoc(doc(student, R + "/doubts/d1"), { deleted: true })));
await t("admin cannot hard-delete", () => assertFails(deleteDoc(doc(admin, R + "/doubts/d1"))));
console.log("blocking devices");
await t("admin blocks a device", () => assertSucceeds(setDoc(doc(admin, R + "/blocked/stud-device-1"), { reason: "abuse", by: "boss", at: now() })));
await t("student cannot block", () => assertFails(setDoc(doc(student, R + "/blocked/other-device-1"), { reason: "x", by: "stud", at: now() })));
await t("blocked device can no longer post", () => assertFails(setDoc(doc(anon, R + "/doubts/dz"), { title: "Hello there", body: "x", subject: "DSP", authorId: "stud-device-1", authorName: "S", createdAt: now() })));
await t("admin unblocks", () => assertSucceeds(deleteDoc(doc(admin, R + "/blocked/stud-device-1"))));
await t("...and the student can post again", () => assertSucceeds(setDoc(doc(anon, R + "/doubts/dy"), { title: "Hello there", body: "x", subject: "DSP", authorId: "stud-device-1", authorName: "S", createdAt: now() })));
console.log("colleges, requests, survey, log");
const college = (extra = {}) => ({ name: "New University", room: "k7Qm2xPa9Rtz", state: "Kerala", campuses: ["MAIN"], subjects: ["Maths"], features: { bot: false }, domains: ["new.edu.in"], requireVerified: false, listed: true, enabled: true, updatedAt: now(), ...extra });
await t("admin creates a college", () => assertSucceeds(setDoc(doc(admin, "colleges/new-university"), college())));
await t("admin edits a college", () => assertSucceeds(setDoc(doc(admin, "colleges/new-university"), college({ tagline: "Learn together" }))));
await t("student cannot write a college", () => assertFails(setDoc(doc(student, "colleges/sneaky"), college())));
await t("college with a bad room id is refused", () => assertFails(setDoc(doc(admin, "colleges/bad-room"), college({ room: "a/b" }))));
await t("college with an unknown field is refused", () => assertFails(setDoc(doc(admin, "colleges/bad-field"), college({ hack: 1 }))));
await t("college with a bad link name is refused", () => assertFails(setDoc(doc(admin, "colleges/Bad_Name"), college())));
await t("admin reads college requests and survey answers", async () => { await assertSucceeds(getDocs(collection(admin, "collegeRequests"))); await assertSucceeds(getDocs(collection(admin, "plusInterest"))); });
await t("students still cannot read requests or survey answers", async () => { await assertFails(getDocs(collection(student, "collegeRequests"))); await assertFails(getDocs(collection(student, "plusInterest"))); });
await t("admin deletes a handled college request", () => assertSucceeds(deleteDoc(doc(admin, "collegeRequests/q1"))));
await t("admin writes an audit entry", () => assertSucceeds(setDoc(doc(admin, "adminLog/l1"), { by: "boss", action: "hide", target: "doubts/d1", room: "rgukt", note: "spam", at: now() })));
await t("audit entries cannot be edited or removed", async () => { await assertFails(updateDoc(doc(admin, "adminLog/l1"), { note: "x" })); await assertFails(deleteDoc(doc(admin, "adminLog/l1"))); });
await t("students cannot read or write the audit log", async () => { await assertFails(getDoc(doc(student, "adminLog/l1"))); await assertFails(setDoc(doc(student, "adminLog/l2"), { by: "s", action: "x", at: now() })); });
await t("admin sets config/plus.required", () => assertSucceeds(setDoc(doc(admin, "config/plus"), { required: true })));
await t("student cannot read config", () => assertFails(getDoc(doc(student, "config/plus"))));
console.log("paper vault");
const paper = (extra = {}) => ({ title: "Data Structures End 2023", subject: "DSA", year: 2023, exam: "End", link: "https://drive.google.com/file/d/abc/view", solution: "", note: "", createdAt: now(), ...extra });
await t("admin adds a paper", () => assertSucceeds(setDoc(doc(admin, R + "/papers/p1"), paper())));
await t("student can read papers", () => assertSucceeds(getDocs(collection(student, R + "/papers"))));
await t("student cannot add a paper", () => assertFails(setDoc(doc(student, R + "/papers/p2"), paper())));
await t("student cannot delete a paper", () => assertFails(deleteDoc(doc(student, R + "/papers/p1"))));
await t("paper with a non-https link is refused", () => assertFails(setDoc(doc(admin, R + "/papers/p3"), paper({ link: "http://x.com/a.pdf" }))));
await t("paper with a javascript link is refused", () => assertFails(setDoc(doc(admin, R + "/papers/p4"), paper({ link: "javascript:alert(1)" }))));
await t("paper with a bad year is refused", () => assertFails(setDoc(doc(admin, R + "/papers/p5"), paper({ year: 1800 }))));
await t("paper with an unknown field is refused", () => assertFails(setDoc(doc(admin, R + "/papers/p6"), paper({ hack: 1 }))));
await t("paper with a solution link is accepted", () => assertSucceeds(setDoc(doc(admin, R + "/papers/p7"), paper({ solution: "https://example.com/sol.pdf" }))));
await t("admin removes a paper", () => assertSucceeds(deleteDoc(doc(admin, R + "/papers/p7"))));
console.log("official notices");
const notice = (extra = {}) => ({ title: "Exam timetable out", body: "Check the portal.", pinned: true, createdAt: now(), ...extra });
await t("admin posts a notice", () => assertSucceeds(setDoc(doc(admin, R + "/notices/n1"), notice())));
await t("notice with a posted-by label is accepted", () => assertSucceeds(setDoc(doc(admin, R + "/notices/n5"), notice({ from: "Exam cell" }))));
await t("notice with a very long posted-by label is refused", () => assertFails(setDoc(doc(admin, R + "/notices/n6"), notice({ from: "x".repeat(60) }))));
await t("student reads notices", () => assertSucceeds(getDocs(collection(student, R + "/notices"))));
await t("student cannot post a notice", () => assertFails(setDoc(doc(student, R + "/notices/n2"), notice())));
await t("notice with a non-https link is refused", () => assertFails(setDoc(doc(admin, R + "/notices/n3"), notice({ link: "javascript:alert(1)" }))));
await t("notice with an unknown field is refused", () => assertFails(setDoc(doc(admin, R + "/notices/n4"), notice({ hack: 1 }))));
await t("admin archives a notice", () => assertSucceeds(setDoc(doc(admin, R + "/notices/n1"), notice({ deleted: true }))));
console.log("referral codes");
const longUid = "abcdefghijklmnopqrstuvwxyz12", rc = env.authenticatedContext(longUid).firestore();
await t("student registers own referral code", () => assertSucceeds(setDoc(doc(rc, "refCodes/abcdefghij"), { uid: longUid, createdAt: now() })));
await t("student cannot register someone else's code", () => assertFails(setDoc(doc(rc, "refCodes/zzzzzzzzzz"), { uid: longUid, createdAt: now() })));
await t("student cannot claim a code for another uid", () => assertFails(setDoc(doc(rc, "refCodes/abcdefghij2"), { uid: "other", createdAt: now() })));
await t("nobody can read or change codes from the app", async () => { await assertFails(getDoc(doc(rc, "refCodes/abcdefghij"))); await assertFails(updateDoc(doc(rc, "refCodes/abcdefghij"), { uid: "x" })); await assertFails(deleteDoc(doc(rc, "refCodes/abcdefghij"))); });
console.log("promo codes");
const promo = (extra = {}) => ({ percent: 30, plan: "any", until: now() + 864e5 * 30, maxUses: 100, used: 0, active: true, note: "Exam season", createdAt: now(), ...extra });
await t("admin creates a promo code", () => assertSucceeds(setDoc(doc(admin, "promoCodes/EXAM30"), promo())));
await t("student cannot read or create promo codes", async () => { await assertFails(getDoc(doc(student, "promoCodes/EXAM30"))); await assertFails(setDoc(doc(student, "promoCodes/FREE90"), promo({ percent: 90 }))); });
await t("promo with 100% off is refused", () => assertFails(setDoc(doc(admin, "promoCodes/FREE100"), promo({ percent: 100 }))));
await t("promo starting with used > 0 is refused", () => assertFails(setDoc(doc(admin, "promoCodes/USED1"), promo({ used: 5 }))));
await t("promo with a lowercase or short code is refused", async () => { await assertFails(setDoc(doc(admin, "promoCodes/exam30x"), promo())); await assertFails(setDoc(doc(admin, "promoCodes/AB"), promo())); });
await t("admin can switch a code off but not change the discount or usage", async () => { await assertSucceeds(updateDoc(doc(admin, "promoCodes/EXAM30"), { active: false })); await assertFails(updateDoc(doc(admin, "promoCodes/EXAM30"), { percent: 90 })); await assertFails(updateDoc(doc(admin, "promoCodes/EXAM30"), { used: 5 })); });
console.log("flash sale");
const sale = (extra = {}) => ({ title: "Flash sale: 30% off", text: "Today only", code: "EXAM30", until: now() + 864e5, active: true, updatedAt: now(), ...extra });
await t("admin sets the flash sale", () => assertSucceeds(setDoc(doc(admin, "sales/current"), sale())));
await t("student reads the flash sale", () => assertSucceeds(getDoc(doc(student, "sales/current"))));
await t("student cannot change the flash sale", () => assertFails(setDoc(doc(student, "sales/current"), sale({ title: "Hacked sale" }))));
await t("only the document 'current' is allowed", () => assertFails(setDoc(doc(admin, "sales/other"), sale())));
await t("a bad code or extra field is refused", async () => { await assertFails(setDoc(doc(admin, "sales/current"), sale({ code: "bad code!" }))); await assertFails(setDoc(doc(admin, "sales/current"), sale({ hack: 1 }))); });
await t("admin switches the sale off", () => assertSucceeds(setDoc(doc(admin, "sales/current"), sale({ active: false }))));
console.log("college staff");
const R2 = "rooms/other-room-77";
await env.withSecurityRulesDisabled(async (c) => { const db = c.firestore(); await setDoc(doc(db, R2 + "/doubts/x1"), { title: "Hello there", body: "x", subject: "DSP", authorId: "dev-x", ownerUid: "someone", authorName: "S", createdAt: now(), reports: [] }); });
const staffUid = "staffmember123456", sctx = env.authenticatedContext(staffUid, { email: "t@college.edu", email_verified: true }).firestore();
const staffDoc = { uid: staffUid, room: "r00m-Abc123xy", slug: "demo", name: "Demo College", label: "Exam cell", by: "boss", createdAt: now() };
await t("student cannot make themselves staff", () => assertFails(setDoc(doc(student, "staff/r00m-Abc123xy_stud"), { ...staffDoc, uid: "stud" })));
await t("admin adds a staff member", () => assertSucceeds(setDoc(doc(admin, "staff/r00m-Abc123xy_" + staffUid), staffDoc)));
await t("staff doc id must match room and uid", () => assertFails(setDoc(doc(admin, "staff/wrong-id"), staffDoc)));
await t("staff member can read their own roster entry (by query)", async () => { const { query, where } = await import("firebase/firestore"); await assertSucceeds(getDocs(query(collection(sctx, "staff"), where("uid", "==", staffUid)))); });
await t("staff member cannot read everyone's entries", () => assertFails(getDocs(collection(sctx, "staff"))));
await t("staff hides a post in their own college", () => assertSucceeds(updateDoc(doc(sctx, R + "/doubts/d1"), { deleted: true })));
await t("staff cannot edit post text", () => assertFails(updateDoc(doc(sctx, R + "/doubts/d1"), { title: "Changed by staff" })));
await t("staff cannot hide a post in another college", () => assertFails(updateDoc(doc(sctx, R2 + "/doubts/x1"), { deleted: true })));
await t("staff posts a notice and a paper for their college", async () => { await assertSucceeds(setDoc(doc(sctx, R + "/notices/s1"), notice())); await assertSucceeds(setDoc(doc(sctx, R + "/papers/s1"), paper())); });
await t("staff cannot post a notice for another college", () => assertFails(setDoc(doc(sctx, R2 + "/notices/s2"), notice())));
await t("staff blocks a device in their college only", async () => { await assertSucceeds(setDoc(doc(sctx, R + "/blocked/bad-device-9"), { reason: "abuse", by: staffUid, at: now() })); await assertFails(setDoc(doc(sctx, R2 + "/blocked/bad-device-9"), { reason: "abuse", by: staffUid, at: now() })); });
await t("staff cannot touch colleges, promos, sales or the roster", async () => { await assertFails(setDoc(doc(sctx, "colleges/staff-college"), college())); await assertFails(setDoc(doc(sctx, "promoCodes/STAFF50"), promo())); await assertFails(setDoc(doc(sctx, "sales/current"), sale())); await assertFails(setDoc(doc(sctx, "staff/r00m-Abc123xy_other"), { ...staffDoc, uid: "other" })); });
const staffNoVerify = env.authenticatedContext(staffUid, { email: "t@college.edu", email_verified: false }).firestore();
await t("staff with an unverified email has no powers", () => assertFails(setDoc(doc(staffNoVerify, R + "/notices/s3"), notice())));
await t("admin removes the staff member and the powers stop", async () => { await assertSucceeds(deleteDoc(doc(admin, "staff/r00m-Abc123xy_" + staffUid))); await assertFails(setDoc(doc(sctx, R + "/notices/s4"), notice())); });
console.log("report e-mails");
const repDoc = (extra = {}) => ({ room: "r00m-Abc123xy", name: "Demo College", emails: ["principal@demo.edu"], active: true, updatedAt: now(), ...extra });
await t("admin sets up report e-mails", () => assertSucceeds(setDoc(doc(admin, "reportEmails/demo"), repDoc())));
await t("student cannot read or write report settings", async () => { await assertFails(getDoc(doc(student, "reportEmails/demo"))); await assertFails(setDoc(doc(student, "reportEmails/evil"), repDoc())); });
await t("more than 5 recipients is refused", () => assertFails(setDoc(doc(admin, "reportEmails/many"), repDoc({ emails: ["a@x.com", "b@x.com", "c@x.com", "d@x.com", "e@x.com", "f@x.com"] }))));
await t("a bad room id is refused", () => assertFails(setDoc(doc(admin, "reportEmails/bad"), repDoc({ room: "a/b" }))));
console.log("placement drives");
await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), "staff/r00m-Abc123xy_" + staffUid), staffDoc); });
const drive = (extra = {}) => ({ company: "Infosys", role: "Systems Engineer", package: "3.6 LPA", branches: ["CSE", "ECE"], minCgpa: 6.5, lastDate: now() + 864e5 * 5, link: "https://example.com/apply", details: "Online test then interview.", createdAt: now(), ...extra });
await t("placement staff posts a drive", () => assertSucceeds(setDoc(doc(sctx, R + "/drives/d1"), drive())));
await t("admin posts a drive", () => assertSucceeds(setDoc(doc(admin, R + "/drives/d2"), drive({ company: "TCS" }))));
await t("student cannot post a drive", () => assertFails(setDoc(doc(student, R + "/drives/d3"), drive())));
await t("staff cannot post a drive for another college", () => assertFails(setDoc(doc(sctx, R2 + "/drives/d4"), drive())));
await t("drive with a javascript link or bad CGPA is refused", async () => { await assertFails(setDoc(doc(sctx, R + "/drives/d5"), drive({ link: "javascript:alert(1)" }))); await assertFails(setDoc(doc(sctx, R + "/drives/d6"), drive({ minCgpa: 11 }))); });
const interest = (extra = {}) => ({ driveId: "d1", uid: "stud", name: "Revi", branch: "CSE", cgpa: 7.8, phone: "9876543210", createdAt: now(), ...extra });
await t("student registers interest in a drive", () => assertSucceeds(setDoc(doc(student, R + "/driveInterest/d1_stud"), interest())));
await t("student cannot register for someone else or a missing drive", async () => { await assertFails(setDoc(doc(student, R + "/driveInterest/d1_other"), interest({ uid: "other" }))); await assertFails(setDoc(doc(student, R + "/driveInterest/nodrive_stud"), interest({ driveId: "nodrive" }))); });
await t("student reads own interest but not others'", async () => { await assertSucceeds(getDoc(doc(student, R + "/driveInterest/d1_stud"))); await assertFails(getDoc(doc(anon, R + "/driveInterest/d1_stud"))); });
await t("placement staff and admin read all applicants", async () => { await assertSucceeds(getDocs(collection(sctx, R + "/driveInterest"))); await assertSucceeds(getDocs(collection(admin, R + "/driveInterest"))); });
await t("a student cannot list all applicants", () => assertFails(getDocs(collection(student, R + "/driveInterest"))));
await t("student withdraws their interest", () => assertSucceeds(deleteDoc(doc(student, R + "/driveInterest/d1_stud"))));
console.log("weekly leaderboard");
const wk = (extra = {}) => ({ week: "w2900", uid: "stud", name: "Revi", points: 120, mins: 100, tests: 2, createdAt: now() - 864e5, updatedAt: now(), ...extra });
await t("student writes their own weekly score", () => assertSucceeds(setDoc(doc(student, R + "/weekly/w2900_stud"), wk())));
await t("student updates their own score", () => assertSucceeds(setDoc(doc(student, R + "/weekly/w2900_stud"), wk({ points: 160 }))));
await t("student cannot write someone else's row", () => assertFails(setDoc(doc(student, R + "/weekly/w2900_other"), wk({ uid: "other" }))));
await t("absurd points are refused", () => assertFails(setDoc(doc(student, R + "/weekly/w2900_stud"), wk({ points: 99999 }))));
await t("an old week row cannot be faked into this week (createdAt too old)", () => assertFails(setDoc(doc(student, R + "/weekly/w2900_stud"), wk({ createdAt: now() - 864e5 * 40 }))));
await t("everyone signed in reads the board", () => assertSucceeds(getDocs(collection(anon, R + "/weekly"))));
await t("student removes only their own row", async () => { await assertSucceeds(deleteDoc(doc(student, R + "/weekly/w2900_stud"))); await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), R + "/weekly/w2900_zed"), wk({ uid: "zed" })); }); await assertFails(deleteDoc(doc(student, R + "/weekly/w2900_zed"))); });
console.log("events and RSVP");
await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), "staff/r00m-Abc123xy_" + staffUid), staffDoc); });
const ev = (extra = {}) => ({ title: "Hackathon kickoff", club: "Coding Club", venue: "Main hall", details: "Bring a laptop.", startAt: now() + 864e5 * 3, capacity: 100, link: "https://example.com/e", createdAt: now(), ...extra });
await t("staff posts an event", () => assertSucceeds(setDoc(doc(sctx, R + "/events/e1"), ev())));
await t("student cannot post an event", () => assertFails(setDoc(doc(student, R + "/events/e2"), ev())));
await t("event with a bad link or capacity is refused", async () => { await assertFails(setDoc(doc(sctx, R + "/events/e3"), ev({ link: "javascript:x" }))); await assertFails(setDoc(doc(sctx, R + "/events/e4"), ev({ capacity: -1 }))); });
await t("student RSVPs and everyone can read RSVPs", async () => { await assertSucceeds(setDoc(doc(student, R + "/eventRsvp/e1_stud"), { eventId: "e1", uid: "stud", name: "Revi", createdAt: now() })); await assertSucceeds(getDocs(collection(anon, R + "/eventRsvp"))); });
await t("student cannot RSVP as someone else or to a missing event", async () => { await assertFails(setDoc(doc(student, R + "/eventRsvp/e1_other"), { eventId: "e1", uid: "other", name: "X", createdAt: now() })); await assertFails(setDoc(doc(student, R + "/eventRsvp/nope_stud"), { eventId: "nope", uid: "stud", name: "Revi", createdAt: now() })); });
await t("student cancels own RSVP but not another's", async () => { await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), R + "/eventRsvp/e1_zed"), { eventId: "e1", uid: "zed", name: "Z", createdAt: now() }); }); await assertFails(deleteDoc(doc(student, R + "/eventRsvp/e1_zed"))); await assertSucceeds(deleteDoc(doc(student, R + "/eventRsvp/e1_stud"))); });
console.log("college bundle");
const lic = (extra = {}) => ({ name: "Demo College", seats: 1200, pricePerStudent: 45, amount: 54000, startAt: now(), until: now() + 864e5 * 365, contact: "principal@demo.edu", notes: "Pilot converted", updatedAt: now(), ...extra });
await t("admin records a licence and switches the college on", async () => { await assertSucceeds(setDoc(doc(admin, "licenses/demo"), lic())); await assertSucceeds(setDoc(doc(admin, "collegePlus/demo"), { name: "Demo College", until: now() + 864e5 * 365, updatedAt: now() })); });
await t("students can read the college switch but not the licence", async () => { await assertSucceeds(getDoc(doc(student, "collegePlus/demo"))); await assertFails(getDoc(doc(student, "licenses/demo"))); });
await t("students and staff cannot change licences or the switch", async () => { await assertFails(setDoc(doc(student, "collegePlus/free"), { name: "X", until: now() + 1e10, updatedAt: now() })); await assertFails(setDoc(doc(sctx, "collegePlus/free2"), { name: "X", until: now() + 1e10, updatedAt: now() })); await assertFails(setDoc(doc(sctx, "licenses/free"), lic())); });
await t("a licence with an unknown field or negative seats is refused", async () => { await assertFails(setDoc(doc(admin, "licenses/bad1"), lic({ hack: 1 }))); await assertFails(setDoc(doc(admin, "licenses/bad2"), lic({ seats: -5 }))); });
await t("admin ends the bundle", () => assertSucceeds(deleteDoc(doc(admin, "collegePlus/demo"))));
console.log("welcome note");
await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), "staff/r00m-Abc123xy_" + staffUid), staffDoc); });
const wn = (extra = {}) => ({ text: "Welcome to our campus family. Study hard and be kind.", from: "Principal", active: true, updatedAt: now(), ...extra });
await t("staff posts the welcome note", () => assertSucceeds(setDoc(doc(sctx, R + "/welcomeMsg/current"), wn())));
await t("admin updates it and students read it", async () => { await assertSucceeds(setDoc(doc(admin, R + "/welcomeMsg/current"), wn({ text: "Best wishes for the exams!" }))); await assertSucceeds(getDoc(doc(student, R + "/welcomeMsg/current"))); });
await t("student cannot write it; other ids and long text are refused", async () => { await assertFails(setDoc(doc(student, R + "/welcomeMsg/current"), wn())); await assertFails(setDoc(doc(admin, R + "/welcomeMsg/other"), wn())); await assertFails(setDoc(doc(admin, R + "/welcomeMsg/current"), wn({ text: "x".repeat(300) }))); });
await t("staff cannot write another college's note", () => assertFails(setDoc(doc(sctx, R2 + "/welcomeMsg/current"), wn())));
console.log("server-only collections");
await t("gifts, referrals, entitlements and payments cannot be read or written from the app", async () => { for (const p of ["gifts/ABCDEFGHJKLM", "referrals/x", "refStats/x", "payments/p1", "aiUsage/u_1"]) { await assertFails(getDoc(doc(student, p))); await assertFails(setDoc(doc(student, p), { x: 1 })); } await assertFails(setDoc(doc(student, "entitlements/stud"), { plan: "plus", until: now() + 1e10 })); });
console.log(`\n${pass} passed, ${fail} failed`);
await env.cleanup(); process.exit(fail ? 1 : 0);
