import { initializeTestEnvironment, assertSucceeds, assertFails } from "@firebase/rules-unit-testing";
import { readFileSync } from "fs";
import { doc, setDoc, getDoc, updateDoc, deleteDoc, collection, getDocs } from "firebase/firestore";
const env = await initializeTestEnvironment({ projectId: "demo-test", firestore: { rules: readFileSync("../../firestore.rules", "utf8"), host: "127.0.0.1", port: 8081 } });
await env.clearFirestore();
let pass = 0, fail = 0;
const t = async (name, fn) => { try { await fn(); pass++; console.log("  ok  ", name); } catch (e) { fail++; console.log("  FAIL", name, "-", String(e.message).slice(0, 120)); } };
const R = "rooms/r00m-Abc123xy", now = () => Date.now();
const anonU = env.authenticatedContext("u1").firestore();                                // signed in (anonymous-style)
const verU = env.authenticatedContext("u2", { email: "ravi@strict.edu.in", email_verified: true }).firestore();
const out = env.unauthenticatedContext().firestore();
const me = "device-id-123456";
const post = (extra = {}) => ({ title: "Z transform doubt", body: "details here", subject: "DSP", authorId: me, authorName: "Ravi", anonymous: false, urgent: false, createdAt: now(), pages: [], fileAttachments: [], ...extra });
console.log("posts and replies");
await t("signed-in student can post a doubt", () => assertSucceeds(setDoc(doc(anonU, R + "/doubts/d1"), post())));
await t("signed-out cannot post", () => assertFails(setDoc(doc(out, R + "/doubts/d2"), post())));
await t("post with unknown field is refused", () => assertFails(setDoc(doc(anonU, R + "/doubts/d3"), post({ evil: 1 }))));
await t("post with old timestamp is refused", () => assertFails(setDoc(doc(anonU, R + "/doubts/d4"), post({ createdAt: now() - 99999999 }))));
await t("jobs post with company/deadline/link is accepted", () => assertSucceeds(setDoc(doc(anonU, R + "/jobs/j1"), post({ type: "Internship", subject: undefined, company: "TCS", deadline: "2030-01-01", applyUrl: "https://x.com", pay: "10k" }).constructor === Object ? (() => { const p = post({ company: "TCS", deadline: "2030-01-01", applyUrl: "https://x.com", pay: "10k", type: "Internship" }); delete p.subject; return p; })() : {})));
await t("reply to a doubt is accepted", () => assertSucceeds(setDoc(doc(anonU, R + "/replies/r1"), { parentId: "d1", parentColl: "doubts", body: "use partial fractions", authorId: me, authorName: "Ravi", anonymous: false, createdAt: now(), pages: [], fileAttachments: [] })));
await t("author can soft-delete (deleted:true) and report", async () => { await assertSucceeds(updateDoc(doc(anonU, R + "/doubts/d1"), { deleted: true })); await assertSucceeds(updateDoc(doc(anonU, R + "/doubts/d1"), { reports: ["u|o"] })); });
await t("hard delete is refused", () => assertFails(deleteDoc(doc(anonU, R + "/doubts/d1"))));
console.log("ownership");
await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), R + "/doubts/own1"), post({ ownerUid: "u1", reports: ["x"] })); });
await t("a post created with someone else's ownerUid is refused", () => assertFails(setDoc(doc(anonU, R + "/doubts/own2"), post({ ownerUid: "u2" }))));
await t("a post created with my own ownerUid is accepted", () => assertSucceeds(setDoc(doc(anonU, R + "/doubts/own3"), post({ ownerUid: "u1" }))));
await t("owner can edit own post", () => assertSucceeds(updateDoc(doc(anonU, R + "/doubts/own1"), { title: "Edited title ok" })));
await t("another student cannot edit it", () => assertFails(updateDoc(doc(verU, R + "/doubts/own1"), { title: "Hacked title ok" })));
await t("another student cannot hide it", () => assertFails(updateDoc(doc(verU, R + "/doubts/own1"), { deleted: true })));
await t("another student can add a report", () => assertSucceeds(updateDoc(doc(verU, R + "/doubts/own1"), { reports: ["x", "u2|o"] })));
await t("...but cannot remove reports", () => assertFails(updateDoc(doc(verU, R + "/doubts/own1"), { reports: [] })));
await t("...or add many reports at once", () => assertFails(updateDoc(doc(verU, R + "/doubts/own1"), { reports: ["x", "u2|o", "a", "b"] })));
await t("...or change another field together with a report", () => assertFails(updateDoc(doc(verU, R + "/doubts/own1"), { reports: ["x", "u2|o", "u2|a"], title: "Sneaky title" })));
await t("owner cannot transfer the post to someone else", () => assertFails(updateDoc(doc(anonU, R + "/doubts/own1"), { ownerUid: "u2" })));
console.log("stories, answers, profiles");
const story = (extra) => ({ authorId: me, authorName: "Ravi", createdAt: now(), ...extra });
await t("text story", () => assertSucceeds(setDoc(doc(anonU, R + "/stories/s1"), story({ kind: "text", text: "tip", bg: "2" }))));
await t("quiz story with options, answer and explanation", () => assertSucceeds(setDoc(doc(anonU, R + "/stories/s2"), story({ kind: "quiz", text: "Unit of capacitance?", opts: ["H", "F"], ans: 1, expl: "C=Q/V", bg: "4" }))));
await t("quiz story with bad answer index is refused", () => assertFails(setDoc(doc(anonU, R + "/stories/s3"), story({ kind: "quiz", text: "q", opts: ["a", "b"], ans: 5 }))));
await t("share story with ref and caption", () => assertSucceeds(setDoc(doc(anonU, R + "/stories/s4"), story({ kind: "share", text: "title", caption: "body", ref: "doubts/d1", bg: "4" }))));
await t("idea story with 300-char details", () => assertSucceeds(setDoc(doc(anonU, R + "/stories/s5"), story({ kind: "idea", text: "idea", caption: "x".repeat(300) }))));
await t("photo story needs pageId", () => assertFails(setDoc(doc(anonU, R + "/stories/s6"), story({ kind: "photo" }))));
await t("story answer (id = story_uid)", () => assertSucceeds(setDoc(doc(anonU, R + "/storyAnswers/s2_" + me), { storyId: "s2", uid: me, name: "Ravi", to: "creator-id-1", campus: "MAIN", pick: 1, ok: true, createdAt: now() })));
await t("story answer with wrong id is refused", () => assertFails(setDoc(doc(anonU, R + "/storyAnswers/zzz"), { storyId: "s2", uid: me, name: "Ravi", to: "creator-id-1", campus: "", pick: 1, ok: true, createdAt: now() })));
await t("story view", () => assertSucceeds(setDoc(doc(anonU, R + "/storyViews/s2_" + me), { storyId: "s2", uid: me, name: "Ravi", createdAt: now() })));
const prof = (db, extra) => setDoc(doc(db, R + "/profiles/" + me + (db === verU ? "-v" : "")), { name: "Ravi", dp: "", status: "Studying", updatedAt: now(), ownerUid: db === verU ? "u2" : "u1", ...extra });
await t("profile with status and dp", () => assertSucceeds(prof(anonU, { dp: "data:image/jpeg;base64," + "A".repeat(100) })));
await t("profile verified:true needs a verified email", () => assertFails(prof(anonU, { verified: true })));
await t("profile verified:true with a verified email", () => assertSucceeds(prof(verU, { verified: true })));
await t("profile plus:true without a paid plan is refused", () => assertFails(prof(verU, { plus: true })));
await t("non-jpeg dp is refused", () => assertFails(prof(anonU, { dp: "data:image/svg+xml;base64,AAAA" })));
console.log("colleges, requests, plus");
await t("anyone can read a college", () => assertSucceeds(getDoc(doc(out, "colleges/anu"))));
await t("nobody can write a college", () => assertFails(setDoc(doc(anonU, "colleges/anu"), { name: "x", room: "abcdefgh" })));
await t("college request (signed in)", () => assertSucceeds(setDoc(doc(anonU, "collegeRequests/c1"), { name: "My College", city: "Guntur", role: "Student", contact: "", consent: true, createdAt: now() })));
await t("college request without consent is refused", () => assertFails(setDoc(doc(anonU, "collegeRequests/c2"), { name: "My College", city: "", role: "Student", contact: "", consent: false, createdAt: now() })));
await t("college requests cannot be read by students", () => assertFails(getDoc(doc(anonU, "collegeRequests/c1"))));
await t("plus interest answer", () => assertSucceeds(setDoc(doc(anonU, "plusInterest/p1"), { email: "", college: "RGUKT", features: ["AI doubt helper"], price: "₹49 a month", createdAt: now() })));
await t("entitlements: cannot write own plan", () => assertFails(setDoc(doc(verU, "entitlements/u2"), { plan: "plus", until: now() + 99999999 })));
await t("entitlements: can read own, not others", async () => { await assertSucceeds(getDoc(doc(verU, "entitlements/u2"))); await assertFails(getDoc(doc(verU, "entitlements/u1"))); });
await t("backup needs a verified email", async () => { await assertFails(setDoc(doc(anonU, "userData/u1"), { json: "{}", updatedAt: now() })); await assertSucceeds(setDoc(doc(verU, "userData/u2"), { json: '{"v":1}', updatedAt: now() })); });
await t("backup readable only by its owner", async () => { await assertSucceeds(getDoc(doc(verU, "userData/u2"))); await assertFails(getDoc(doc(anonU, "userData/u2"))); });
await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), "config/plus"), { required: true }); });
await t("backup becomes a paid feature when config/plus.required is true", () => assertFails(setDoc(doc(verU, "userData/u2"), { json: '{"v":2}', updatedAt: now() })));
await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), "entitlements/u2"), { plan: "plus", until: now() + 864e5 * 30 }); });
await t("...and works again with an active plan", () => assertSucceeds(setDoc(doc(verU, "userData/u2"), { json: '{"v":3}', updatedAt: now() })));
await t("profile plus:true accepted with an active plan", () => assertSucceeds(prof(verU, { verified: true, plus: true })));
console.log("device block and verified-only college");
await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), R + "/blocked/" + me), { reason: "abuse" }); });
await t("blocked device cannot post", () => assertFails(setDoc(doc(anonU, R + "/doubts/dB"), post())));
await t("blocked device cannot reply or add a story", async () => { await assertFails(setDoc(doc(anonU, R + "/replies/rB"), { parentId: "d1", parentColl: "doubts", body: "hi hi", authorId: me, authorName: "R", anonymous: false, createdAt: now(), pages: [], fileAttachments: [] })); await assertFails(setDoc(doc(anonU, R + "/stories/sB"), story({ kind: "text", text: "x" }))); });
await t("someone else is not blocked", () => assertSucceeds(setDoc(doc(anonU, R + "/doubts/dOk"), post({ authorId: "other-device-1" }))));
await env.withSecurityRulesDisabled(async (c) => { await setDoc(doc(c.firestore(), "colleges/strict"), { name: "Strict", room: "college-strict", requireVerified: true, domains: ["strict.edu.in"] }); });
const SR = "rooms/college-strict";
await t("requireVerified: unverified cannot post", () => assertFails(setDoc(doc(anonU, SR + "/doubts/a1"), post({ authorId: "x-device-123" }))));
await t("requireVerified: wrong-domain email cannot post", async () => { const w = env.authenticatedContext("u3", { email: "a@gmail.com", email_verified: true }).firestore(); await assertFails(setDoc(doc(w, SR + "/doubts/a2"), post({ authorId: "y-device-123" }))); });
await t("requireVerified: right-domain verified email can post", () => assertSucceeds(setDoc(doc(verU, SR + "/doubts/a3"), post({ authorId: "z-device-123" }))));
await t("requireVerified: everyone can still read", () => assertSucceeds(getDocs(collection(anonU, SR + "/doubts"))));
await t("a college without requireVerified is open", () => assertSucceeds(setDoc(doc(anonU, "rooms/college-open/doubts/o1"), post({ authorId: "w-device-123" }))));
console.log(`\n${pass} passed, ${fail} failed`);
await env.cleanup(); process.exit(fail ? 1 : 0);
